# -*- coding: utf-8 -*-
"""news_parsing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OPEuWLZwsfZ6KkAfrmTv7S_ZFzFQxH6e
"""

!pip install beautifulsoup4

!pip install requests

from bs4 import BeautifulSoup
import requests
import pandas as pd

url = 'https://rostec.ru/'
page = requests.get(url)

print(page.status_code)

allNews = []

soup = BeautifulSoup(page.text, "html.parser")

print(soup)

from pandas._libs import index
allNews_date = pd.DataFrame(soup.findAll('span', class_="date"))
allNews_text = pd.DataFrame(soup.findAll('span', class_="text"))
allNews=pd.concat([allNews_date,allNews_text],axis=1)
#allNews=allNews_date.join(allNews_text, how='left')
print(allNews)

data=pd.DataFrame(allNews)
data.info()
data.head()

data.columns = ['date', '0', '1', '2', 'title', '4', '5', '6']

data1 = data.drop(['0', '1', '2', '4', '5', '6'], axis=1)
data1

data1.sort_values(by='date',ascending=True,kind='quicksort')
data1.info()
data1.tail()

data1.head()

